# favicon path to your logo
favicon:

# canvas
canvasbg:
    enabled: false
    color:
    opacity:
    count:

# personal links
## links icon base folder
linkiconbase: /images/links/
## array of links
links:
    - name:xuanye
      link:https://github.com/xuanye/
      icon:github.png

# pagination
pagination:
    prev_text: '<'
    next_text: '>'

# whether to display `CC BY-SA 4.0` declaration
declaration: true

# comment
waline:
    enabled: true
    serverURL: blog-api-ecru.vercel.app
    placeholder:
    avatar:
    emoji:
        bilibili: true
        qq: true
        tieba: true
        twitter: true
        alus: true
        weibo: true

# footer
## for users in China
icp:
## visitor counter
counter:
    enabled: true

# google site verification
verimeta:
